name: jest

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  jest:

    runs-on: ubuntu-latest
    permissions:
      contents: write  # for Git to git apply

    steps:
      - uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install node modules
        run: |
          npm install
          sudo apt-get install xvfb

      - name: Run tests
        run: xvfb-run npm test
